package com.ykkoo.pet.common.type;

public enum FileType {
    ALL,
    ROTATION_CHART,
    INSURANCE_BRIEF,
    INSURANCE_DETAILS,
    SECURITY_CARD,
    HOSPITAL_HEAD_PORTRAIT,
    HOSPITAL_DETAILS_PIC,
    HOSPITAL_BUSINESS_LICENSE,
    CLAIM_INVOICE,
    CLAIM_DIAGNOSIS,
    CLAIM_VOUCHER,
    DIAGNOSTIC_VOUCHER,
    IDENTITY_CARD_INFO,
    BANK_CARD_INFO;


}


